local session = require("game.session")

describe("game.session", function()
  it("new() initializes scores and match bookkeeping", function()
    local s = session.new()
    local a, b = s:get_scores()
    assert.equals(0, a)
    assert.equals(0, b)
    assert.equals(0, s.matches_completed)
    assert.is_nil(s.last_match_winner)
  end)

  it("bump_match_win increments winner score and matches_completed", function()
    local s = session.new()
    s:bump_match_win(2)
    local a, b = s:get_scores()
    assert.equals(0, a)
    assert.equals(1, b)
    assert.equals(1, s.matches_completed)
    assert.equals(2, s.last_match_winner)
  end)
end)
