local terrain_gen = require("sim.terrain_gen")

describe("sim.terrain_gen", function()
  it("build returns terrain and spawns for fixed seed", function()
    local r = terrain_gen.build(4242, nil, nil, nil, nil, nil)
    assert.is_not_nil(r)
    assert.is_not_nil(r.terrain)
    assert.are.equal(5, #r.spawns_p1)
    assert.are.equal(5, #r.spawns_p2)
    assert.is_number(r.seed_used)
  end)

  it("build is deterministic for the same seed", function()
    local a = terrain_gen.build(9001, nil, nil, nil, nil, nil)
    local b = terrain_gen.build(9001, nil, nil, nil, nil, nil)
    assert.are.equal(a.seed_used, b.seed_used)
    assert.are.equal(a.spawns_p1[1].x, b.spawns_p1[1].x)
    assert.are.equal(a.spawns_p1[1].y, b.spawns_p1[1].y)
  end)
end)
