local Timer = require("util.timer")

describe("util.timer", function()
  it("completes after duration and stays done", function()
    local t = Timer.new(0.5)
    assert.is_false(t:update(0.2))
    assert.is_false(t.done)
    assert.is_true(t:update(0.4))
    assert.is_true(t.done)
    assert.is_true(t:update(1))
    assert.is_true(t.done)
  end)

  it("ratio climbs to 1", function()
    local t = Timer.new(1)
    t:update(0.25)
    assert.is_true(math.abs(t:ratio() - 0.25) < 1e-9)
    t:update(2)
    assert.are.equal(1, t:ratio())
  end)

  it("reset clears progress", function()
    local t = Timer.new(1)
    t:update(1)
    assert.is_true(t.done)
    t:reset(2)
    assert.is_false(t.done)
    assert.are.equal(0, t.t)
    assert.are.equal(2, t.duration)
  end)
end)
