local timer = require("core.timer")

describe("core.timer", function()
  it("countdown reaches done after dt", function()
    local t = timer.countdown(1)
    t:update(0.4)
    assert.is_false(t:done())
    t:update(0.7)
    assert.is_true(t:done())
    assert.equals(0, t.t)
  end)

  it("reset sets time again", function()
    local t = timer.countdown(0.5)
    t:update(1)
    t:reset(2)
    assert.equals(2, t.t)
    assert.is_false(t:done())
  end)
end)
