local vec2 = require("core.vec2")

describe("core.vec2", function()
  it("add / sub / scale", function()
    local a = vec2.new(1, 2)
    local b = vec2.new(3, 4)
    local s = vec2.add(a, b)
    assert.equals(4, s.x)
    assert.equals(6, s.y)
    local d = vec2.sub(b, a)
    assert.equals(2, d.x)
    assert.equals(2, d.y)
    local sc = vec2.scale(a, 3)
    assert.equals(3, sc.x)
    assert.equals(6, sc.y)
  end)

  it("len and norm", function()
    assert.equals(5, vec2.len(vec2.new(3, 4)))
    local z = vec2.norm(vec2.new(0, 0))
    assert.equals(0, z.x)
    assert.equals(0, z.y)
    local n = vec2.norm(vec2.new(3, 4))
    assert.is_true(math.abs(n.x - 0.6) < 1e-6)
    assert.is_true(math.abs(n.y - 0.8) < 1e-6)
  end)

  it("dist", function()
    assert.equals(5, vec2.dist(vec2.new(0, 0), vec2.new(3, 4)))
  end)
end)
