local weapons = require("data.weapons")

describe("data.weapons", function()
  it("defines rocket and grenade with expected ids", function()
    assert.equals("rocket", weapons.rocket.id)
    assert.equals("grenade", weapons.grenade.id)
    assert.is_true(weapons.rocket.speed > weapons.grenade.speed)
    assert.is_true(weapons.grenade.blast_radius >= weapons.rocket.blast_radius)
  end)
end)
